module "checkpoint" {
  source  = "../modules/terraform-nva-into-existing-hub"

authentication_method           = "Azure CLI"
client_secret                   = "n/a"
client_id                       = "n/a"
tenant_id                       = "n/a"
subscription_id                 = "d350e7f2-578e-496d-b94e-9b4e7e136b56"
resource-group-name             = "rg-non-prod-vwaninfra-swe"
location                        = "Sweden Central"
vwan-hub-name                   = "vhub-non-prod-infra-swc-001"
vwan-hub-resource-group         = "rg-non-prod-vwaninfra-swe"
managed-app-name                = "tf-vwan-managed-app-nva"
nva-rg-name                     = "tf-vwan-nva-rg"
nva-name                        = "tf-vwan-nva"
os-version                      = "R8120"
license-type                    = "Security Enforcement (NGTP)"
scale-unit                      = "2"
bootstrap-script                = "touch /home/admin/bootstrap.txt; echo 'hello_world' > /home/admin/bootstrap.txt"
admin-shell                     = "/etc/cli.sh"
sic-key                         = "4gH2rPq8JkT9WxY"
ssh-public-key                  = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfsrs7E5SlOE5/9TJej0KvFXLtLba34wYVPCg/fZqNsjK7Bv9YqxWeo6aduClO9/l+9GiaPdo0/C8IPaqhIJvIwnNrpyj9SihnUTesCR9TqMKgiXlGmefV/gZmmFh8b3JKL56Qck011ypgIeIMoFRb5RzXBN+NBDMnXNlplkqrb7T92IGBrwQK2pGFUT/PGkHj/z5M5kRwxK1b8gNulvuNs/cZiCQjZWFeGea3lhyfq4hZx+bPWWOiht+U9uBg2PjCVzPzsrEui1/uMibRSMwPmzySW5zlT0GH+QpvT6SnO0yfBJBCAtkd8b0DW2MnfnWnjNDEhKvL9QEfirO6CCJz rsa-key-20240902"
bgp-asn                         = "64512"
custom-metrics                  = "yes"
routing-intent-internet-traffic = "yes"
routing-intent-private-traffic  = "yes"
smart1-cloud-token-a            = ""
smart1-cloud-token-b            = ""
smart1-cloud-token-c            = ""
smart1-cloud-token-d            = ""
smart1-cloud-token-e            = ""   
existing-public-ip              = ""
new-public-ip                   = "yes"
}